import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar1 } from "@/components/layout/navbar";
import { ThemeProvider } from "@/providers/theme-provider";
import './globals.css';
import { Button } from "@/components/ui/button";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        {/* <Navbar1/> */}
        {/* <div className="flex gap-2">
        <Button asChild><Link href="/about">About</Link></Button>
        <Button asChild><Link href="/blog">Blog</Link></Button>
        <Button asChild><Link href="/set">Settings</Link></Button>
       </div> */}


        {children}
      </ThemeProvider>
      
      </body>
    </html>
  );
}
